import { Method } from "./types";

export const methods: Method[] = [
  {
    id: "pildora",
    name: "Píldora anticonceptiva",
    category: "hormonal",
    effectiveness: 91,
    description: "Pastilla que se toma diariamente y contiene hormonas que previenen la ovulación.",
    howItWorks: "Contiene estrógeno y progestina (o solo progestina) que impiden la liberación del óvulo, espesan el moco cervical y adelgazan el revestimiento uterino.",
    pros: [
      "Altamente efectiva con uso correcto",
      "Puede regular el ciclo menstrual",
      "Reduce cólicos y acné en algunos casos",
      "Reversible al dejar de tomarla",
    ],
    cons: [
      "Hay que tomarla todos los días a la misma hora",
      "Puede causar efectos secundarios (náuseas, cambios de humor)",
      "No protege contra ITS",
      "Requiere receta médica",
    ],
  },
  {
    id: "diu-hormonal",
    name: "DIU Hormonal",
    category: "hormonal",
    effectiveness: 99,
    description: "Pequeño dispositivo en forma de T que se coloca en el útero y libera hormonas.",
    howItWorks: "Libera levonorgestrel que espesa el moco cervical, adelgaza el endometrio y en algunos casos suprime la ovulación.",
    pros: [
      "Dura 3-7 años según el tipo",
      "Muy efectivo, no requiere recordar nada",
      "Puede reducir o eliminar el sangrado menstrual",
      "Reversible al retirarlo",
    ],
    cons: [
      "Requiere inserción por profesional médico",
      "Puede causar dolor durante la inserción",
      "Posibles efectos secundarios hormonales",
      "No protege contra ITS",
    ],
  },
  {
    id: "diu-cobre",
    name: "DIU de Cobre",
    category: "barrier",
    effectiveness: 99,
    description: "Dispositivo en forma de T sin hormonas que se coloca en el útero.",
    howItWorks: "El cobre crea un ambiente que es tóxico para los espermatozoides, impidiendo la fecundación.",
    pros: [
      "Dura hasta 10-12 años",
      "Sin hormonas",
      "Puede usarse como anticoncepción de emergencia",
      "Muy efectivo",
    ],
    cons: [
      "Puede aumentar el sangrado y los cólicos",
      "Requiere inserción profesional",
      "No protege contra ITS",
    ],
  },
  {
    id: "condon",
    name: "Condón masculino",
    category: "barrier",
    effectiveness: 82,
    description: "Funda delgada que se coloca sobre el pene erecto antes de la relación sexual.",
    howItWorks: "Barrera física que impide que los espermatozoides lleguen al óvulo.",
    pros: [
      "Protege contra ITS y embarazo",
      "Fácil de conseguir sin receta",
      "Sin efectos secundarios hormonales",
      "Económico",
    ],
    cons: [
      "Puede romperse o deslizarse",
      "Requiere uso en cada relación",
      "Algunas personas son alérgicas al látex",
    ],
  },
  {
    id: "implante",
    name: "Implante subdérmico",
    category: "hormonal",
    effectiveness: 99,
    description: "Pequeña varilla flexible que se inserta bajo la piel del brazo.",
    howItWorks: "Libera progestina continuamente, suprimiendo la ovulación y espesando el moco cervical.",
    pros: [
      "Dura 3-5 años",
      "Uno de los métodos más efectivos",
      "No requiere recordar nada",
      "Reversible al retirarlo",
    ],
    cons: [
      "Puede causar sangrado irregular",
      "Requiere procedimiento para inserción y retiro",
      "No protege contra ITS",
      "Posibles efectos secundarios",
    ],
  },
  {
    id: "inyeccion",
    name: "Inyección anticonceptiva",
    category: "hormonal",
    effectiveness: 94,
    description: "Inyección de progestina que se aplica cada 1-3 meses.",
    howItWorks: "La progestina suprime la ovulación y espesa el moco cervical.",
    pros: [
      "Solo requiere visita médica cada 1-3 meses",
      "Discreta",
      "Puede reducir el sangrado menstrual",
    ],
    cons: [
      "Puede causar aumento de peso",
      "Puede tardar en volver la fertilidad al dejarla",
      "No protege contra ITS",
      "Posible pérdida de densidad ósea con uso prolongado",
    ],
  },
  {
    id: "parche",
    name: "Parche anticonceptivo",
    category: "hormonal",
    effectiveness: 91,
    description: "Parche adhesivo que se coloca en la piel y libera hormonas.",
    howItWorks: "Libera estrógeno y progestina a través de la piel para prevenir la ovulación.",
    pros: [
      "Se cambia solo una vez por semana",
      "Fácil de usar",
      "Reversible",
    ],
    cons: [
      "Visible en la piel",
      "Puede despegarse",
      "Efectos secundarios similares a la píldora",
      "No protege contra ITS",
    ],
  },
  {
    id: "ritmo",
    name: "Método del ritmo / Calendario",
    category: "natural",
    effectiveness: 76,
    description: "Seguimiento del ciclo menstrual para identificar los días fértiles y evitar relaciones en esos días.",
    howItWorks: "Se calculan los días fértiles basándose en la duración de ciclos anteriores para evitar relaciones sin protección durante la ventana fértil.",
    pros: [
      "Sin hormonas ni dispositivos",
      "Sin costo",
      "Ayuda a conocer tu cuerpo",
    ],
    cons: [
      "Menos efectivo que otros métodos",
      "Requiere ciclos regulares",
      "Requiere disciplina y registro constante",
      "No protege contra ITS",
    ],
  },
];
